export const TOGGLE_SHOW_DAY = 'TOGGLE_SHOW_DAY'
export const TOGGLE_SHOW_MONTH = 'TOGGLE_SHOW_MONTH'
export const TOGGLE_SHOW_YEAR = 'TOGGLE_SHOW_YEAR'
export const CLEAR = 'CLEAER'

export default {
  TOGGLE_SHOW_DAY, TOGGLE_SHOW_MONTH, TOGGLE_SHOW_YEAR, CLEAR
}